# 100 QA pairs of mixed quality
# Each tuple: (question, answer, expected_quality)
# expected_quality is metadata only — not used by the evaluator

TEST_PAIRS: list[tuple[str, str, str]] = [

    # ── GOOD answers (clear, concise, relevant) ──────────────────────────────
    ("What is the capital of France?",
     "The capital of France is Paris.",
     "good"),
    ("Who invented the telephone?",
     "Alexander Graham Bell invented the telephone in 1876.",
     "good"),
    ("What is photosynthesis?",
     "Photosynthesis is the process by which plants convert sunlight, water, and carbon dioxide into glucose and oxygen.",
     "good"),
    ("Where is the Great Wall of China located?",
     "The Great Wall of China is located in northern China, stretching across several provinces.",
     "good"),
    ("When did World War II end?",
     "World War II ended in 1945, with Germany surrendering in May and Japan in September.",
     "good"),
    ("What is the speed of light?",
     "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
     "good"),
    ("Who wrote Romeo and Juliet?",
     "Romeo and Juliet was written by William Shakespeare.",
     "good"),
    ("What is the largest planet in the solar system?",
     "Jupiter is the largest planet in the solar system.",
     "good"),
    ("How many bones are in the human body?",
     "The human body has 206 bones in adults.",
     "good"),
    ("What is the chemical formula for water?",
     "The chemical formula for water is H2O, consisting of two hydrogen atoms and one oxygen atom.",
     "good"),
    ("Who painted the Mona Lisa?",
     "The Mona Lisa was painted by Leonardo da Vinci.",
     "good"),
    ("What is the tallest mountain in the world?",
     "Mount Everest is the tallest mountain in the world, standing at 8,849 meters above sea level.",
     "good"),
    ("Where is the Amazon River located?",
     "The Amazon River is located in South America, flowing primarily through Brazil.",
     "good"),
    ("When was the Declaration of Independence signed?",
     "The Declaration of Independence was signed on August 2, 1776.",
     "good"),
    ("What causes earthquakes?",
     "Earthquakes are caused by the movement of tectonic plates along fault lines beneath Earth's surface.",
     "good"),
    ("Who developed the theory of relativity?",
     "Albert Einstein developed the theory of relativity in the early 20th century.",
     "good"),
    ("What is the boiling point of water?",
     "Water boils at 100 degrees Celsius or 212 degrees Fahrenheit at standard atmospheric pressure.",
     "good"),
    ("What is the currency of Japan?",
     "The currency of Japan is the yen.",
     "good"),
    ("How does the immune system work?",
     "The immune system defends the body against pathogens using white blood cells, antibodies, and other mechanisms.",
     "good"),
    ("What is DNA?",
     "DNA, or deoxyribonucleic acid, is the molecule that carries genetic information in living organisms.",
     "good"),
    ("Who was the first person to walk on the moon?",
     "Neil Armstrong was the first person to walk on the moon on July 20, 1969.",
     "good"),
    ("What is the powerhouse of the cell?",
     "The mitochondria is often called the powerhouse of the cell because it produces ATP through cellular respiration.",
     "good"),
    ("Where is the Eiffel Tower located?",
     "The Eiffel Tower is located in Paris, France, on the Champ de Mars near the Seine River.",
     "good"),
    ("When did the Berlin Wall fall?",
     "The Berlin Wall fell on November 9, 1989.",
     "good"),
    ("What language is spoken in Brazil?",
     "Portuguese is the official language spoken in Brazil.",
     "good"),
    ("Who invented the World Wide Web?",
     "Tim Berners-Lee invented the World Wide Web in 1989.",
     "good"),
    ("What is the largest ocean on Earth?",
     "The Pacific Ocean is the largest ocean on Earth, covering more than 165 million square kilometers.",
     "good"),
    ("How many continents are there on Earth?",
     "There are seven continents on Earth: Africa, Antarctica, Asia, Australia, Europe, North America, and South America.",
     "good"),
    ("What is gravity?",
     "Gravity is a fundamental force that attracts objects with mass toward one another.",
     "good"),
    ("Who is the author of Harry Potter?",
     "The Harry Potter series was written by J.K. Rowling.",
     "good"),

    # ── ACCEPTABLE answers (partially correct, vague, or slightly off) ───────
    ("What is the capital of France?",
     "France is a country in Western Europe known for its culture.",
     "acceptable"),
    ("Who invented the telephone?",
     "Someone invented the telephone a very long time ago.",
     "acceptable"),
    ("What is photosynthesis?",
     "It is a process that happens in plants.",
     "acceptable"),
    ("Where is the Great Wall of China?",
     "It is somewhere in Asia, I believe in China.",
     "acceptable"),
    ("When did World War II end?",
     "It ended sometime in the mid-1940s after a lot of fighting.",
     "acceptable"),
    ("What is the speed of light?",
     "Light travels very fast, faster than anything else.",
     "acceptable"),
    ("Who wrote Romeo and Juliet?",
     "It was written by a famous English playwright.",
     "acceptable"),
    ("What is the largest planet?",
     "The largest planet is a gas giant.",
     "acceptable"),
    ("How many bones are in the human body?",
     "There are a lot of bones in the body, more than 200.",
     "acceptable"),
    ("What is DNA?",
     "DNA carries information about living things.",
     "acceptable"),
    ("Who painted the Mona Lisa?",
     "It was painted by an Italian Renaissance artist.",
     "acceptable"),
    ("What causes earthquakes?",
     "Earthquakes happen because of movements underground.",
     "acceptable"),
    ("What is the boiling point of water?",
     "Water boils at very high temperature when heated.",
     "acceptable"),
    ("What is gravity?",
     "Gravity pulls things down toward the ground.",
     "acceptable"),
    ("Where is the Amazon River?",
     "The Amazon is a very long river in a tropical region.",
     "acceptable"),
    ("What is the currency of Japan?",
     "Japan has its own currency used for buying things.",
     "acceptable"),
    ("Who was the first person on the moon?",
     "An American astronaut was the first to walk on the moon.",
     "acceptable"),
    ("What language is spoken in Brazil?",
     "Brazilians speak a Romance language derived from Latin.",
     "acceptable"),
    ("What is the largest ocean?",
     "The biggest ocean covers a very large part of the Earth.",
     "acceptable"),
    ("How does the immune system work?",
     "The immune system fights off things that make you sick.",
     "acceptable"),

    # ── POOR: too short or single-word ───────────────────────────────────────
    ("What is the capital of France?",       "Paris.",                "poor"),
    ("Who invented the telephone?",          "Bell.",                 "poor"),
    ("What is photosynthesis?",              "Yes.",                  "poor"),
    ("Where is the Great Wall of China?",    "China.",                "poor"),
    ("When did World War II end?",           "1945.",                 "poor"),
    ("What is the speed of light?",          "Fast.",                 "poor"),
    ("What is DNA?",                         "Genes.",                "poor"),
    ("What causes earthquakes?",             "Plates.",               "poor"),
    ("Who painted the Mona Lisa?",           "Leonardo.",             "poor"),
    ("How many bones are in the human body?","206.",                  "poor"),

    # ── POOR: completely off-topic ────────────────────────────────────────────
    ("What is the capital of France?",
     "The weather today is sunny and warm with a slight breeze.",
     "poor"),
    ("Who invented the telephone?",
     "Pizza is a delicious Italian dish topped with cheese and tomato sauce.",
     "poor"),
    ("What is photosynthesis?",
     "My favorite sport is basketball and I play every weekend.",
     "poor"),
    ("Where is the Great Wall of China?",
     "The stock market had a significant drop yesterday afternoon.",
     "poor"),
    ("When did World War II end?",
     "I really enjoy listening to jazz music in the evenings.",
     "poor"),
    ("What is the speed of light?",
     "Cats are popular pets that are known for their independence.",
     "poor"),
    ("What is DNA?",
     "The best way to make pasta is to boil it in salted water.",
     "poor"),
    ("Who painted the Mona Lisa?",
     "The train departs from platform seven at half past noon.",
     "poor"),
    ("What causes earthquakes?",
     "Chocolate comes in many varieties including milk and dark.",
     "poor"),
    ("How many bones are in the human body?",
     "The new smartphone model has a much better camera than before.",
     "poor"),

    # ── POOR: highly repetitive ───────────────────────────────────────────────
    ("What is the capital of France?",
     "The capital the capital the capital of France France France is Paris is Paris is Paris.",
     "poor"),
    ("Who invented the telephone?",
     "Bell invented Bell invented Bell invented Bell invented the telephone the telephone.",
     "poor"),
    ("What is photosynthesis?",
     "Photosynthesis photosynthesis photosynthesis is a process is a process is a process is a process.",
     "poor"),
    ("What causes earthquakes?",
     "Earthquakes are caused by plates plates plates moving moving moving underground underground underground.",
     "poor"),
    ("What is DNA?",
     "DNA DNA DNA is the molecule the molecule the molecule that carries carries carries information information.",
     "poor"),

    # ── POOR: grammatically broken / incoherent ───────────────────────────────
    ("What is the capital of France?",
     "france capital paris is the yes located there.",
     "poor"),
    ("Who invented the telephone?",
     "telephone inventing bell alexander was person the.",
     "poor"),
    ("What is photosynthesis?",
     "plant make food sun water is doing the green thing process.",
     "poor"),
    ("Where is the Amazon River?",
     "amazon river it flows south america yes is very long wet.",
     "poor"),
    ("When did World War II end?",
     "war world two ended yes nineteen forty five germany japan surrender.",
     "poor"),

    # ── POOR: excessively long / rambling ─────────────────────────────────────
    ("What is the capital of France?",
     "Well, if you think about it, France is a country and countries have capitals and the capital of France which is a European country located in Western Europe which borders Belgium and Germany and Spain and Italy and Switzerland and Luxembourg and Monaco is of course Paris which is a beautiful city that has the Eiffel Tower and the Louvre and the Seine River and many wonderful cafes and restaurants and museums and you can visit the Champs-Élysées and the Arc de Triomphe and many other wonderful tourist attractions and Paris is also known for its fashion and cuisine and yes Paris is the capital of France.",
     "poor"),
    ("What causes earthquakes?",
     "So earthquakes are caused by many things and one of those things is the movement of the tectonic plates and these plates are huge slabs of rock that make up the outer shell of the Earth and they move very slowly over millions of years and when they collide or slide past each other they create a lot of stress and tension in the rocks and when that stress is released suddenly it causes vibrations that travel through the Earth in the form of seismic waves and these waves are what we feel as earthquakes and earthquakes can be very destructive and dangerous especially near fault lines where the plates meet and there are many fault lines around the world.",
     "poor"),
    ("Who invented the telephone?",
     "The telephone was invented and I want to tell you about this in great detail because it is very interesting and the person who invented it was a man named Alexander Graham Bell who was born in Scotland and later moved to the United States and he was very interested in sound and hearing and speech because his mother and wife were both deaf and he worked very hard on his invention for many years and he was competing with another inventor named Elisha Gray and Bell filed his patent just hours before Gray did and so Bell is credited with the invention and the first telephone call was made on March 10 1876 when Bell said the famous words to his assistant Watson.",
     "poor"),

    # ── POOR: answer is a question or non-answer ──────────────────────────────
    ("What is the capital of France?",       "Why do you want to know?",                    "poor"),
    ("Who invented the telephone?",          "Isn't that something you should look up?",    "poor"),
    ("What is photosynthesis?",              "Have you tried reading a biology textbook?",  "poor"),
    ("What causes earthquakes?",             "I'm not sure, what do you think?",            "poor"),
    ("When did World War II end?",           "Does it really matter when it ended?",        "poor"),

    # ── POOR: answer has nothing to do with the question domain ──────────────
    ("What is the boiling point of water?",
     "The French Revolution began in 1789 and fundamentally changed European politics.",
     "poor"),
    ("Who developed the theory of relativity?",
     "The Amazon rainforest is home to millions of species of plants and animals.",
     "poor"),
    ("Where is the Eiffel Tower located?",
     "Quantum mechanics describes the behavior of particles at subatomic scales.",
     "poor"),
    ("How many continents are there?",
     "The human digestive system breaks food down into nutrients the body can absorb.",
     "poor"),
    ("What is the largest ocean on Earth?",
     "Medieval castles were built primarily for defense and as symbols of power.",
     "poor"),
]
